### ISSUE TITLE
Game hang when killing a Skeleton Horse

### ISSUE THREAD

**Issue by brisingraerowing** [Lothrazar/GameRuleConfig#7]
Minecraft Version: 1.16.4

Forge Version: 35.1.13

Mod Version: 1.0.2

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):

I have a mod that can spawn Skeleton Horses with a Skeleton riding them (not a Skeleton Trap). I killed the Skeleton, then tried to kill the horse (as I already have 10 of them), and the game promptly hung and I had to kill the process.

Log file link: https://gist.github.com/BrisingrAerowing/9e7277c66020bb963e5202a5eb7cb90c

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Error is from " corgiaoc.byg.mixin.MixinConnector", so im not sure if this is me. Is there a mod name or mod author under  corgiaoc.byg

**Comment by brisingraerowing** [comment]
BYG is Biomes You Go, which I don't have installed. That's just from another mod that does something with it (not sure which one). The actual error is at the end of the file (which Github doesn't show as the file is too long).

```text
[28Dec2020 10:52:32.556] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.NullPointerException: null
	at com.lothrazar.customgamerules.event.RuleEvents.onLivingAttackEvent(RuleEvents.java:412) ~[customgamerules:1.16.3-1.0.2]
	at net.minecraftforge.eventbus.ASMEventHandler_703_RuleEvents_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:320) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:932) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(AnimalEntity.java:73) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1100) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerController.func_78764_a(PlayerController.java:352) ~[?:?]
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1305) ~[?:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13-launcher.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by brisingraerowing** [comment]
This also occurs with the Ghost Rat from Rats (which spawns from a sword to do additional damage to a mob). Anything that is tamed but does not have an owner will cause the crash, as you don't check whether the owner UUID is null, as the getOwnerId method will return null if the entity is not owned.

**Comment by Lothrazar** [comment]
Thanks for that new crashlog, helped me solve it.   crash happened when a mob is Tamed = true, but the owner is null, as if its tamed by a null player. anyway this latest release has the fix https://www.curseforge.com/minecraft/mc-mods/custom-game-rules/files/3185331 . 

Re open a new report if anything fails as always
